#!/usr/bin/env node

const Mocha = require("mocha");
const path = require("path");

const [ testPath ] = process.argv.slice(2);

// Instantiate a Mocha instance.
const mocha = new Mocha({
  timeout: 30 * 1000
});

mocha.reporter(function(x, y) {
  // console.log(x);
  console.log(y);

});

console.log("testPath:", testPath);
console.log(process.cwd());
const fullTestPath = path.join(process.cwd(), testPath);
console.log("fullTestPath:", fullTestPath);

mocha.addFile(fullTestPath);

// Run the tests.
const runner = mocha.run((failures) => {
  process.exitCode = failures ? 1 : 0;  // exit with non-zero status if there were failures
});

runner.on("start", (x) => {
  console.log("START:", x);
});

runner.on("ready", (x) => {
  console.log("READY:", x);
});

runner.on("suite", (suite) => {
  console.log("SUITE", suite.fullTitle());
});

runner.on("test", (test) => {
  console.log("TEST", test.fullTitle());
});

runner.on("pass", (test) => {
  console.log("PASSED", test.fullTitle());
});

runner.on("fail", (test) => {
  console.log("FAILED", test.fullTitle());
});

runner.on("end", (x) => {
  console.log("END", x);
});